export const CartActionTypes = {
    SET_HIDDEN_CART: 'SET_HIDDEN_CART',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAN_ITEM_FROM_CART: 'CLEAN_ITEM_FROM_CART',
    CLEAER_CART: 'CLEAER_CART'
};